import type { RankDefinition } from "@/types/ranks";

export const ranks = [
    {
        id: "ant",
        name: "Ant",
        minimumLevel: 1,
        maximumLevel: 4,
    },
    {
        id: "bumblebee",
        name: "Bumblebee",
        minimumLevel: 5,
        maximumLevel: 9,
    },
    {
        id: "mouse",
        name: "Mouse",
        minimumLevel: 10,
        maximumLevel: 14,
    },
    {
        id: "frog",
        name: "Frog",
        minimumLevel: 15,
        maximumLevel: 19,
    },
    {
        id: "starfish",
        name: "Starfish",
        minimumLevel: 20,
        maximumLevel: 24,
    },
    {
        id: "seahorse",
        name: "Seahorse",
        minimumLevel: 25,
        maximumLevel: 29,
    },
    {
        id: "sloth",
        name: "Sloth",
        minimumLevel: 30,
        maximumLevel: 34,
    },
    {
        id: "hedgehog",
        name: "Hedgehog",
        minimumLevel: 35,
        maximumLevel: 39,
    },
    {
        id: "chameleon",
        name: "Chameleon",
        minimumLevel: 40,
        maximumLevel: 44,
    },
    {
        id: "meerkat",
        name: "Meerkat",
        minimumLevel: 45,
        maximumLevel: 49,
    },
    {
        id: "chicken",
        name: "Chicken",
        minimumLevel: 50,
        maximumLevel: 54,
    },
    {
        id: "flamingo",
        name: "Flamingo",
        minimumLevel: 55,
        maximumLevel: 59,
    },
    {
        id: "hare",
        name: "Hare",
        minimumLevel: 60,
        maximumLevel: 64,
    },
    {
        id: "red_panda",
        name: "Red Panda",
        minimumLevel: 65,
        maximumLevel: 69,
    },
    {
        id: "cat",
        name: "Cat",
        minimumLevel: 70,
        maximumLevel: 74,
    },
    {
        id: "dog",
        name: "Dog",
        minimumLevel: 75,
        maximumLevel: 79,
    },
    {
        id: "penguin",
        name: "Penguin",
        minimumLevel: 80,
        maximumLevel: 84,
    },
    {
        id: "seal",
        name: "Seal",
        minimumLevel: 85,
        maximumLevel: 89,
    },
    {
        id: "raccoon",
        name: "Raccoon",
        minimumLevel: 90,
        maximumLevel: 94,
    },
    {
        id: "deer",
        name: "Deer",
        minimumLevel: 95,
        maximumLevel: 99,
    },
    {
        id: "otter",
        name: "Otter",
        minimumLevel: 100,
        maximumLevel: 104,
    },
    {
        id: "koala",
        name: "Koala",
        minimumLevel: 105,
        maximumLevel: 109,
    },
    {
        id: "fox",
        name: "Fox",
        minimumLevel: 110,
        maximumLevel: 114,
    },
    {
        id: "owl",
        name: "Owl",
        minimumLevel: 115,
        maximumLevel: 119,
    },
    {
        id: "panda",
        name: "Panda",
        minimumLevel: 120,
        maximumLevel: 124,
    },
    {
        id: "monkey",
        name: "Monkey",
        minimumLevel: 125,
        maximumLevel: 129,
    },
    {
        id: "parrot",
        name: "Parrot",
        minimumLevel: 130,
        maximumLevel: 134,
    },
    {
        id: "kangaroo",
        name: "Kangaroo",
        minimumLevel: 135,
        maximumLevel: 139,
    },
    {
        id: "badger",
        name: "Badger",
        minimumLevel: 140,
        maximumLevel: 144,
    },
    {
        id: "boar",
        name: "Boar",
        minimumLevel: 145,
        maximumLevel: 149,
    },
    {
        id: "zebra",
        name: "Zebra",
        minimumLevel: 150,
        maximumLevel: 154,
    },
    {
        id: "octopus",
        name: "Octopus",
        minimumLevel: 155,
        maximumLevel: 159,
    },
    {
        id: "dolphin",
        name: "Dolphin",
        minimumLevel: 160,
        maximumLevel: 164,
    },
    {
        id: "lynx",
        name: "Lynx",
        minimumLevel: 165,
        maximumLevel: 169,
    },
    {
        id: "hyena",
        name: "Hyena",
        minimumLevel: 170,
        maximumLevel: 174,
    },
    {
        id: "wolf",
        name: "Wolf",
        minimumLevel: 175,
        maximumLevel: 179,
    },
    {
        id: "alligator",
        name: "Alligator",
        minimumLevel: 180,
        maximumLevel: 184,
    },
    {
        id: "moose",
        name: "Moose",
        minimumLevel: 185,
        maximumLevel: 189,
    },
    {
        id: "giraffe",
        name: "Giraffe",
        minimumLevel: 190,
        maximumLevel: 194,
    },
    {
        id: "turtle",
        name: "Turtle",
        minimumLevel: 195,
        maximumLevel: 199,
    },
    {
        id: "eagle",
        name: "Eagle",
        minimumLevel: 200,
        maximumLevel: 204,
    },
    {
        id: "cheetah",
        name: "Cheetah",
        minimumLevel: 205,
        maximumLevel: 209,
    },
    {
        id: "panther",
        name: "Panther",
        minimumLevel: 210,
        maximumLevel: 214,
    },
    {
        id: "gorilla",
        name: "Gorilla",
        minimumLevel: 215,
        maximumLevel: 219,
    },
    {
        id: "hippopotamus",
        name: "Hippopotamus",
        minimumLevel: 220,
        maximumLevel: 224,
    },
    {
        id: "lion",
        name: "Lion",
        minimumLevel: 225,
        maximumLevel: 229,
    },
    {
        id: "shark",
        name: "Shark",
        minimumLevel: 230,
        maximumLevel: 234,
    },
    {
        id: "tiger",
        name: "Tiger",
        minimumLevel: 235,
        maximumLevel: 239,
    },
    {
        id: "grizzly_bear",
        name: "Grizzly Bear",
        minimumLevel: 240,
        maximumLevel: 244,
    },
    {
        id: "rhino",
        name: "Rhino",
        minimumLevel: 245,
        maximumLevel: 249,
    },
    {
        id: "elephant",
        name: "Elephant",
        minimumLevel: 250,
        maximumLevel: 254,
    },
    {
        id: "whale",
        name: "Whale",
        minimumLevel: 255,
        maximumLevel: 259,
    },
    {
        id: "phoenix",
        name: "Phoenix",
        minimumLevel: 260,
        maximumLevel: 264,
    },
    {
        id: "dragon",
        name: "Dragon",
        minimumLevel: 265,
        maximumLevel: 269,
    },
    {
        id: "hydra",
        name: "Hydra",
        minimumLevel: 270,
        maximumLevel: null,
    },
] as const;
