import type { ImageSourcePropType } from "react-native";

import type { RankId } from "@/types/ranks";

export const ANIMAL_RANK_IMAGES: Record<
    RankId,
    ImageSourcePropType
> = {
    ant: require("../assets/ranks/animals/ant.png"),
    bumblebee: require("../assets/ranks/animals/bumblebee.png"),
    mouse: require("../assets/ranks/animals/mouse.png"),
    frog: require("../assets/ranks/animals/frog.png"),
    starfish: require("../assets/ranks/animals/starfish.png"),
    seahorse: require("../assets/ranks/animals/seahorse.png"),
    sloth: require("../assets/ranks/animals/sloth.png"),
    hedgehog: require("../assets/ranks/animals/hedgehog.png"),
    chameleon: require("../assets/ranks/animals/chameleon.png"),
    meerkat: require("../assets/ranks/animals/meerkat.png"),
    chicken: require("../assets/ranks/animals/chicken.png"),
    flamingo: require("../assets/ranks/animals/flamingo.png"),
    hare: require("../assets/ranks/animals/hare.png"),
    red_panda: require("../assets/ranks/animals/red_panda.png"),
    cat: require("../assets/ranks/animals/cat.png"),
    dog: require("../assets/ranks/animals/dog.png"),
    penguin: require("../assets/ranks/animals/penguin.png"),
    seal: require("../assets/ranks/animals/seal.png"),
    raccoon: require("../assets/ranks/animals/raccoon.png"),
    deer: require("../assets/ranks/animals/deer.png"),
    otter: require("../assets/ranks/animals/otter.png"),
    koala: require("../assets/ranks/animals/koala.png"),
    fox: require("../assets/ranks/animals/fox.png"),
    owl: require("../assets/ranks/animals/owl.png"),
    panda: require("../assets/ranks/animals/panda.png"),
    monkey: require("../assets/ranks/animals/monkey.png"),
    parrot: require("../assets/ranks/animals/parrot.png"),
    kangaroo: require("../assets/ranks/animals/kangaroo.png"),
    badger: require("../assets/ranks/animals/badger.png"),
    boar: require("../assets/ranks/animals/boar.png"),
    zebra: require("../assets/ranks/animals/zebra.png"),
    octopus: require("../assets/ranks/animals/octopus.png"),
    dolphin: require("../assets/ranks/animals/dolphin.png"),
    lynx: require("../assets/ranks/animals/lynx.png"),
    hyena: require("../assets/ranks/animals/hyena.png"),
    wolf: require("../assets/ranks/animals/wolf.png"),
    alligator: require("../assets/ranks/animals/alligator.png"),
    moose: require("../assets/ranks/animals/moose.png"),
    giraffe: require("../assets/ranks/animals/giraffe.png"),
    turtle: require("../assets/ranks/animals/turtle.png"),
    eagle: require("../assets/ranks/animals/eagle.png"),
    cheetah: require("../assets/ranks/animals/cheetah.png"),
    panther: require("../assets/ranks/animals/panther.png"),
    gorilla: require("../assets/ranks/animals/gorilla.png"),
    hippopotamus: require("../assets/ranks/animals/hippopotamus.png"),
    lion: require("../assets/ranks/animals/lion.png"),
    shark: require("../assets/ranks/animals/shark.png"),
    tiger: require("../assets/ranks/animals/tiger.png"),
    grizzly_bear: require("../assets/ranks/animals/grizzly_bear.png"),
    rhino: require("../assets/ranks/animals/rhino.png"),
    elephant: require("../assets/ranks/animals/elephant.png"),
    whale: require("../assets/ranks/animals/whale.png"),
    phoenix: require("../assets/ranks/animals/phoenix.png"),
    dragon: require("../assets/ranks/animals/dragon.png"),
    hydra: require("../assets/ranks/animals/hydra.png"),
};